sonar.projectKey=myitssarpras-new
sonar.projectName=myitssarpras
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=tests

sonar.test.inclusions=tests/**/*.php
sonar.exclusions=vendor/**,node_modules/**,storage/**,bootstrap/cache/**,public/build/**,coverage-html/**

sonar.php.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8
